//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMInsurance.SmsSender.ServiceReferenceSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsMessage", Namespace="http://schemas.datacontract.org/2004/07/Uralsibins.SmsExternalService.EasySms")]
    [System.SerializableAttribute()]
    public partial class SmsMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIdField, value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendingResult", Namespace="http://schemas.datacontract.org/2004/07/Uralsibins.SmsExternalService.EasySms")]
    [System.SerializableAttribute()]
    public partial class SmsSendingResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uralsibins.ru", ConfigurationName="ServiceReferenceSms.IEasySmsService")]
    public interface IEasySmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uralsibins.ru/IEasySmsService/SendMessage", ReplyAction="http://uralsibins.ru/IEasySmsService/SendMessageResponse")]
        OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult SendMessage(OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uralsibins.ru/IEasySmsService/SendMessage", ReplyAction="http://uralsibins.ru/IEasySmsService/SendMessageResponse")]
        System.Threading.Tasks.Task<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult> SendMessageAsync(OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uralsibins.ru/IEasySmsService/SendMessages", ReplyAction="http://uralsibins.ru/IEasySmsService/SendMessagesResponse")]
        System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult> SendMessages(System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage> items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uralsibins.ru/IEasySmsService/SendMessages", ReplyAction="http://uralsibins.ru/IEasySmsService/SendMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult>> SendMessagesAsync(System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage> items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEasySmsServiceChannel : OMInsurance.SmsSender.ServiceReferenceSms.IEasySmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EasySmsServiceClient : System.ServiceModel.ClientBase<OMInsurance.SmsSender.ServiceReferenceSms.IEasySmsService>, OMInsurance.SmsSender.ServiceReferenceSms.IEasySmsService {
        
        public EasySmsServiceClient() {
        }
        
        public EasySmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EasySmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasySmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasySmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult SendMessage(OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage item) {
            return base.Channel.SendMessage(item);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult> SendMessageAsync(OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage item) {
            return base.Channel.SendMessageAsync(item);
        }
        
        public System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult> SendMessages(System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage> items) {
            return base.Channel.SendMessages(items);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsSendingResult>> SendMessagesAsync(System.Collections.Generic.List<OMInsurance.SmsSender.ServiceReferenceSms.SmsMessage> items) {
            return base.Channel.SendMessagesAsync(items);
        }
    }
}
